schema_version = "1.0.0"

id = "blendixserial"
version = "1.3.0"
name = "blendixserial"
tagline = "Connect Blender to External Devices via Simple UART (Serial Communication)"
maintainer = "Usman"
type = "add-on"

 website = "https://electronicstree.com/blendixserial-addon/"
tags = ["Animation", "3D View"]
blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0"]
 copyright = [
   "2023-2025 Usman",
   "2024-2025 electronicstree",
 ]

 platforms = ["windows-x64", "macos-arm64", "linux-x64"]

paths_exclude_pattern = [
   "__pycache__/",
   "/.git/",
   "/*.zip",
 ]